name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: docker build -t react-app .

    #   - name: Push Docker Image to GitHub Container Registry
    #     run: |
    #       echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
    #       docker tag react-app ghcr.io/${{ github.repository }}:latest
    #       docker push ghcr.io/${{ github.repository }}:latest

    #   - name: Deploy (Optional Step)
    #     run: echo "Deploy your app to a hosting platform"
